Implemented NG-YORUBA language translation.
swoocn/map-of-pi-redux pull request #15
Opened 2024-03-23 00:33 UTC by swoocn

Awaiting one more section for translation.  Please review and approve accordingly in the meantime.  Thanks!

2024-03-23 19:06 UTC, DarinHajou approved these changes
Nice work!

2024-03-24 07:44 UTC, zolcsi approved these changes
LGTM

2024-03-24 07:57 UTC, Ahis24 approved these changes
{
  "CORE": {
    "APP_NAME": "Map of Pi"
  },
  "HOME": {
    "ADD_MY_BUSINESS": "Fi Ọjà/Òwò mi l'éde",
    "SEARCH_BAR_PLACEHOLDER": "Wá Ọjà tàbí Òwò..."
  },
  "FOOTER": {
    "PRIVACY_POLICY": "ÌLÀNÀ ÌPA Ọ̀RỌ̀ MỌ́",
    "TERMS_OF_SERVICE": "Májẹ̀mú Àjọṣepọ̀ tàbí Lílo Èròjà yí"
  },
  "INFORMATION_DIALOG": {
    "LATEST_UPDATES": "Àwọn Ìròyìn/Ìkéde Tuntun",
    "REPORTING_MESSAGE": "Ẹjọ̀wọ́ ẹ fi Àlébù/Àṣìṣe Ránṣẹ́ sí"
  },
  "BUSINESS_MARKER_DIALOG": {
    "DISTANCE_MESSAGE": "Tí ó jínà sí ọ̀dọ̀ rẹ",
    "ONLINE_PI_ORDERS_ALLOWED_MESSAGE": "À ńgba fífi owó Pi ra ọjà lórí afẹ́fẹ́",
    "MENU_ITEMS_AVAILABLE_MESSAGE": "Àwọn Èlò Òntẹ̀ Atọ́kún",
    "BUTTONS": {
      "VISIT_SHOP": "Yẹ Olùtajà wò",
      "TAKE_ROUTE": "Gba Ibí Wọlé"
    }
  },
  "BUSINESS": {
    "REGISTRATION": {
      "LABELS": {
        "BUSINESS_NAME": "Orúkọ Òwò/Ilé-Iṣẹ́",
        "BUSINESS_DESCRIPTION": "Ìjúwé nípa Òwò",
        "BUSINESS_TYPE": "Irú Òwò",
        "BUSINESS_TYPES": {
          "RESTAURANT": "Ilé Oúnjẹ",
          "RETAIL_STORE": "Oníṣòwò/Alágbàtà",
          "SERVICE": "Iṣẹ́-ọwọ́",
          "CONSTRUCTION": "Ilé-kíkọ́/Ọ̀nà-Túntúnṣe",
          "TRANSPORTATION": "Awakọ̀"
        },
        "BUSINESS_LOCATION": "Agbègbè tí Òwò náá wà",
        "BUSINESS_IMAGES": "Àwọn Àwòrán nípa Òwò",
        "BUSINESS_PHONE_NUMBER": "Ẹ̀rọ Ìbánisọ̀rọ̀ Olówò/Òṣìsé",
        "BUSINESS_EMAIL_ADDRESS": "Ẹ̀rọ Ìfi-Ọ̀rọ̀ Ránṣẹ́ Ímeèli Olówò/Òṣìṣẹ́"
      },
      "PLACEHOLDERS": {
        "BUSINESS_NAME": "Tẹ Orúkọ Òwò/Iṣẹ́ rẹ s'íbí",
        "BUSINESS_DESCRIPTION": "Ṣe Àlàyé ṣókí nípa Ówó tàbí Iṣẹ́ tí o bá ńṣe s'íbí",
        "BUSINESS_LOCATION": "Ṣe Ìjúwé-agbègbè tí Òwò tàbí Iṣẹ́ rẹ́ wà",
        "BUSINESS_IMAGES": "Fi Àwọn Àworán nípa Iṣẹ́/Òwò rẹ s'íbí",
        "BUSINESS_PHONE_NUMBER": "Tẹ Ẹ̀rọ Ìbánisọ̀rọ̀ nípa Iṣẹ́/Òwò rẹ s'íbí",
        "BUSINESS_EMAIL_ADDRESS": "Tẹ Ẹ̀rọ Ìfi-Ọ̀rọ̀ Ránṣẹ́ Ímeèlì Iṣẹ́ rẹ s'íbí"
      },
      "VALIDATIONS": {
        "BUSINESS_NAME": "O kò tíì fi Orúkọ Òwò síi",
        "BUSINESS_DESCRIPTION": "O kò tíì fi Àlàyé nípa Òwò síi",
        "BUSINESS_TYPE": "O kò tíì fi Irú Òwò síi",
        "BUSINESS_LOCATION": "O kò tíì fi Ìjúwé-agbégbé Òwò/Iṣẹ́ rẹ síi",
        "BUSINESS_IMAGES": "O kò tíì fi àwòrán nípa Òwò/Iṣẹ́ rẹ síi",
        "BUSINESS_PHONE_NUMBER": "O kò tíì fi Ẹ̀rọ-Ìbánísọ̀rọ̀ Iṣẹ́/Òwò rẹ síi",
        "BUSINESS_EMAIL_ADDRESS": "O kò tíì fi Ẹ̀rọ-Àtẹ̀jíṣẹ́ Ímeèli Iṣẹ́ rẹ síi"
      },
      "BUTTONS": {
        "MENU": "Èròja Atọ́kùn",
        "LOYALTY_STAMPS": "Òntẹ̀ Ìṣe-déédé",
        "BUSINESS_PHOTOS": "Àwòrán Nípa Òwò/Iṣẹ́",
        "QR_CODE": "Wo Àwòrán QR Code",
        "CONFIRM": "Fi Ìfiléde Iṣẹ́/Òwò mi Pamọ́",
        "UNDER_CONSTRUCTION": "À ń ṣiṣẹ̀ nípa Èròjà yí l'ọ́wọ́"
      }
    },
    "CONFIGURATION": {
      "LABELS": {
        "SHOP_NAME": "Orúkọ Àyè-Ìtajà",
        "MENU": "Àwọn Èlò Atọ́kùn",
        "ACCEPT_ORDERS_WITHOUT_PAYMENT_MESSAGE": "Gba Ìbèèrè fún Ọjà láì tíì sanwó",
        "ACCEPT_PI_TRANSACTIONS_MESSAGE": "Gba Sísan owó Pi"
      },
      "ADD_PRODUCT_MENU": {
        "LABELS": {
          "ADD_PRODUCT_INTO_SHOP_MESSAGE": "Fi Ọjà sí inú àyè ìtajà rẹ",
          "PRODUCT_NAME": "Orúkọ Ọjà",
          "PRODUCT_IMAGES": "Àwọn Àwòrán Ọjà",
          "ADD_IMAGE": "Fi Àwòrán síi",
          "PRICE": "Iye-owó Ọjà",
          "DESCRIPTION": "Àlàyé nípa Ọjà",
          "FOOD_SERVICE": {
            "TIME_PREPARATION_MESSAGE": "Iye Ìṣẹ́jú tí Óunjẹ yí á tó dé lẹ̀?"
          }
        },
        "BUTTONS": {
          "LOADING": "Ó ń kójọpọ̀ lọ́wọ́..",
          "CONFIRM": "Ó dára": ""
        }
      }
    },
    "ADD_PRODUCT": {
      "LABELS": {
        "PRODUCT_NAME": "Orúkọ Ọjà",
        "PRODUCT_DESCRIPTION": "Àlàyé Ṣókí nípa Ọjà yí",
        "PRODUCT_IMAGES": "Àwọn Àwòrán nípa Ọjà yí",
        "PRODUCT_PRICE": "Iye Owó Ọjà",
        "PRODUCT_QUANTITY": "Iye Ónka Ọjà",
        "SHIPPING_TYPE": "Àwọn Oríṣí Ọ̀nà làti fi Ọjà ránṣẹ́ sí Olùrajà"
      },
      "PLACEHOLDERS": {
        "PRODUCT_IMAGES": "Tẹ ibí láti fi Àwọn Àwòrán nípa Ọjà rẹ síi",
        "PRODUCT_IMAGES_MAX": "Ó kéré jù, Àwòrán Mẹ́ta(tàbí Jubẹ́ẹ́lọ)"
      },
      "VALIDATIONS": {
        "PRODUCT_IMAGES": "O kò tíì fi Àwòrán nípa Ọjà rẹ síì"
      },
      "OPTIONS": {
        "SHIPPING_TYPES": {
          "FREE_SHIPPING": "Fífi Ọjà Ránṣe sí Olùrajà l'ọ́fẹ̀",
          "PAID_SHIPPING": "Sísan Owó Ìfi Ọjà Ránṣẹ́",
          "PICKUP": "Kí Olùrajà wá Gba Ọjà rẹ̀ nì Ilé-Iṣẹ́ wa",
          "PAY_ON_DELIVERY": "Kí Olùrajà san owó Ọjà lẹ́yìn Ìgbà tí a bá gbé Ọjà rẹ̀ lọ fún"
        }
      },
      "BUTTONS": {
        "SUBMIT": "Ó ti parí"
      }
    }
  },
  "SHOPPING": {
    "ORDER_SCREEN": {
      "MENU": "Àwọn Èlò Atọ́kùn",
      "HIGHLIGHT_MESSAGE": "O le ràá lórí afẹ́fẹ́ kí o sanwó lójú-kojú",
      "BUY_NOW_MESSAGE": "Ràá báyì",
      "NO_PRODUCTS_MESSAGE": "Olùtajà yí kò ní Ọjà kankan."
    }
  },
  "PRIVACY_POLICY": {
    "TITLE": "ÌLÀNÀ ÌPA Ọ̀RỌ̀ MỌ́",
    "LAST_UPDATED": "Ìgbà tí a ṣe àtúnṣe kányìn",
    "EMAIL_ADDRESS": "Ẹ̀rọ Àtẹ̀jíṣẹ́ Ímèèlì wa",
    "SECTIONS": {
      "HEADER_1": "Àlàyé Nípa Àkọ́lé yí",
      "CONTENT_1": "Ẹ káábọ̀ sí inú Èròja Káràkátà Map of Pi, èyí tí àwọn Ìgbìmọ Map of Pi dá sílẹ̀, ní Ìfọwọ́sowọ́pọ̀ gbogbo àwùjọ àti àwọn ìkànì Pi. Ìlànà Ìpa Ọ̀rọ̀ mọ́ yí ṣàlàyé bí a ṣe má n gba ọ̀rọ̀, lo ọ̀rọ̀, ṣàfihàn ọ̀rọ̀, àti bí a ṣe má n dáàbò bo àwọn àtẹ̀jíṣẹ́ ọ̀rọ̀ yín nígbà tí ẹ bá n lo Èròja Káràkátà wa.",

      "HEADER_2": "Àwọn Ọ̀rọ̀ tí à ń Gbà",
      "SUBHEADER_2_1": "Ọ̀rọ̀ nípa Ẹni tí ó ńlo Èròjà yí",
      "CONTENT_2_1_1": "Tí ẹ bá fi Orúkọ sílẹ̀ gẹ́gẹ́ bí Olùlo-Èròja Káràkátà yí, a máa ní láti gba Orúkọ yín, Ẹ̀rọ Àtẹ̀jíṣẹ́ Íméélì yín, Àlàjẹ́ tàbí Àpèmọ́-Orúkọ yín, àti àwọn Ọ̀rọ̀ pàtàkì míràn.",
      "CONTENT_2_1_2": "Fún raraarẹ̀ ni Èròja Káràkátà yí máa ní láti gba àwọn Ọ̀rọ̀-àtọ́kasí nípa Ẹ̀rọ Ayára-bí àṣá yín, bíi Irúu Ẹ̀rọ tí ó bá jẹ́, Irúu Irinṣẹ́ àìfojúrí tí ó fí n ṣisẹ́, àti àwọn ọ̀rọ̀ ìtọ́kasí pàtàkì nípa rẹ̀.",
      "SUBHEADER_2_2": "Àwọn Ọ̀rọ̀ Olùtajà",
      "CONTENT_2_2_1": "Àwọn Olùtajà tí wọn ń fi Orúkọ s'ílẹ̀ nínúu Èròja Káràkátà yí máa ní láti fi àwọn Ọ̀rọ̀ nípa Òwò/Iṣẹ́/Ilé-iṣẹ́ wọn s'ílẹ̀, bíi Orúkọ Òwò/Iṣẹ́/Ilé-iṣẹ́ wọn, Agbègbè tí ó wà, àti àwọn ẹ̀rọ ìbánisọ̀rọ̀ tàbí ìlànà láti kàn síwọn.",

      "HEADER_3": "Bí a ṣe máa ńlo àwón Ọ̀rọ̀ tí ẹ fi s'ílẹ̀",
      "SUBHEADER_3_1": "Láti fi ṣe Ìpèsè/Àlékún/Àtúnṣe Iṣẹ́ wa",
      "CONTENT_3_1_1": "À ńlo àwọn ọ̀rọ̀ tí ẹ fi s'ílẹ̀ láti fi ṣe Ìpèsè, Àtúnṣe àti Àlékún iṣẹ́ wa nínú Èròja Káràkátà Map of Pi, bíi gbogbo àwọn èèlò tí Olúrajà àti Olútajà máa máa lò nínúu Èròja Káràkátà yí.",
      "SUBHEADER_3_2": "Ọ̀nà Ìkànsíra-Ẹni",
      "CONTENT_3_2_1": "A máa lo Ẹ̀rọ Àtẹ̀jíṣẹ́ Ímeèlì yín láti máa fún yín ní àwọn Ìròyìn, Àkíyèsí, àti àwọn Ọ̀nà Ìtẹ̀síwájú nípa Èròja Káràkátà Map of Pi.",
      "SUBHEADER_3_3": "Àtúpalẹ̀",
      "CONTENT_3_3_1": "A má ńṣe Àtúpalẹ̀ àwọn Ọ̀rọ̀ tí a gbà làti fi ṣe Àtúnṣe ọnà ìgbàṣiṣẹ́, àwọn èèlò, àti àwọn ǹkan míràn nípa Èròja Káràkátà yi.",

      "HEADER_4": "Ṣíṣe Àfihàn Àwọn Ọ̀rọ̀ tí ẹ fi s'ílẹ̀",
      "SUBHEADER_4_1": "Fún/Pẹ̀lúu Àwọn Olùtajà",
      "CONTENT_4_1_1": "A máa ṣ'àfihàn àwọn Ọ̀rọ̀ tí Olùrajà bá fi s'ílẹ̀ fún àwọn Olùtajà, láti lòó fún mímọ irúu Ọjà tí wọn fẹ́ tà fúnwọn, àti bí wọ́n ṣe máa kàn sí wọn.",
      "SUBHEADER_4_2": "Pẹ̀lúu Ẹnì Kẹ̀ta tàbí Ilé-iṣẹ́ míràn",
      "CONTENT_4_2_1": "A lè ní láti lo àwọn Ọ̀rọ̀ tí a gbà fún ìṣàfihàn pẹ̀lúu Ilé-iṣẹ́ míràn, fún síse-dáada Ẹ̀ròja Káràkátà yí, àti fún Àtúpalẹ̀, àti fùn àwọn ètò pẹ̀lú ílànà láti san owó.",

      "HEADER_5": "Ìgbésẹ̀ Nípa Ètò-Àbò",
      "CONTENT_5_1": "A ti ṣe ètò àbò orì-afẹ́fẹ́ tí ó múná dóko, láti dáábò bo àwọn ọ̀rọ̀ àti ìfiléde yín. Síbẹ̀síbẹ̀ náà, kò tíì sí ìfi-ọ̀rọ̀ ránṣẹ́ tàbí ìfi-ọ̀rọ̀ pamọ́ lóríi ìtàkùn ayélujàra tàbí lóríi afẹ́fẹ́, tí ètò àbo rẹ̀ dájú tán.",

      "HEADER_6": "Àwọn Àṣàyàn Rẹ",
      "CONTENT_6_1": "O lè ṣe àtúnkọ tàbí kí o pa àwọn ọ̀rọ̀-ìfiléde rẹ rẹ́, nì inúu èèlo-ètò Èròjà yí. Tí o bá sì fẹ́, o lè wọ́gi lé àwọn àtẹ̀jìṣẹ́ ì [...]

2024-03-24 08:05 UTC, Ahis24 requested changes
{
  "CORE": {
    "APP_NAME": "Map of Pi"
  },
  "HOME": {
    "ADD_MY_BUSINESS": "Fi Ọjà/Òwò mi l'éde",
    "SEARCH_BAR_PLACEHOLDER": "Wá Ọjà tàbí Òwò..."
  },
  "FOOTER": {
    "PRIVACY_POLICY": "ÌLÀNÀ ÌPA Ọ̀RỌ̀ MỌ́",
    "TERMS_OF_SERVICE": "Májẹ̀mú Àjọṣepọ̀ tàbí Lílo Èròjà yí"
  },
  "INFORMATION_DIALOG": {
    "LATEST_UPDATES": "Àwọn Ìròyìn/Ìkéde Tuntun",
    "REPORTING_MESSAGE": "Ẹjọ̀wọ́ ẹ fi Àlébù/Àṣìṣe Ránṣẹ́ sí"
  },
  "BUSINESS_MARKER_DIALOG": {
    "DISTANCE_MESSAGE": "Tí ó jínà sí ọ̀dọ̀ rẹ",
    "ONLINE_PI_ORDERS_ALLOWED_MESSAGE": "À ńgba fífi owó Pi ra ọjà lórí afẹ́fẹ́",
    "MENU_ITEMS_AVAILABLE_MESSAGE": "Àwọn Èlò Òntẹ̀ Atọ́kún",
    "BUTTONS": {
      "VISIT_SHOP": "Yẹ Olùtajà wò",
      "TAKE_ROUTE": "Gba Ibí Wọlé"
    }
  },
  "BUSINESS": {
    "REGISTRATION": {
      "LABELS": {
        "BUSINESS_NAME": "Orúkọ Òwò/Ilé-Iṣẹ́",
        "BUSINESS_DESCRIPTION": "Ìjúwé nípa Òwò",
        "BUSINESS_TYPE": "Irú Òwò",
        "BUSINESS_TYPES": {
          "RESTAURANT": "Ilé Oúnjẹ",
          "RETAIL_STORE": "Oníṣòwò/Alágbàtà",
          "SERVICE": "Iṣẹ́-ọwọ́",
          "CONSTRUCTION": "Ilé-kíkọ́/Ọ̀nà-Túntúnṣe",
          "TRANSPORTATION": "Awakọ̀"
        },
        "BUSINESS_LOCATION": "Agbègbè tí Òwò náá wà",
        "BUSINESS_IMAGES": "Àwọn Àwòrán nípa Òwò",
        "BUSINESS_PHONE_NUMBER": "Ẹ̀rọ Ìbánisọ̀rọ̀ Olówò/Òṣìsé",
        "BUSINESS_EMAIL_ADDRESS": "Ẹ̀rọ Ìfi-Ọ̀rọ̀ Ránṣẹ́ Ímeèli Olówò/Òṣìṣẹ́"
      },
      "PLACEHOLDERS": {
        "BUSINESS_NAME": "Tẹ Orúkọ Òwò/Iṣẹ́ rẹ s'íbí",
        "BUSINESS_DESCRIPTION": "Ṣe Àlàyé ṣókí nípa Ówó tàbí Iṣẹ́ tí o bá ńṣe s'íbí",
        "BUSINESS_LOCATION": "Ṣe Ìjúwé-agbègbè tí Òwò tàbí Iṣẹ́ rẹ́ wà",
        "BUSINESS_IMAGES": "Fi Àwọn Àworán nípa Iṣẹ́/Òwò rẹ s'íbí",
        "BUSINESS_PHONE_NUMBER": "Tẹ Ẹ̀rọ Ìbánisọ̀rọ̀ nípa Iṣẹ́/Òwò rẹ s'íbí",
        "BUSINESS_EMAIL_ADDRESS": "Tẹ Ẹ̀rọ Ìfi-Ọ̀rọ̀ Ránṣẹ́ Ímeèlì Iṣẹ́ rẹ s'íbí"
      },
      "VALIDATIONS": {
        "BUSINESS_NAME": "O kò tíì fi Orúkọ Òwò síi",
        "BUSINESS_DESCRIPTION": "O kò tíì fi Àlàyé nípa Òwò síi",
        "BUSINESS_TYPE": "O kò tíì fi Irú Òwò síi",
        "BUSINESS_LOCATION": "O kò tíì fi Ìjúwé-agbégbé Òwò/Iṣẹ́ rẹ síi",
        "BUSINESS_IMAGES": "O kò tíì fi àwòrán nípa Òwò/Iṣẹ́ rẹ síi",
        "BUSINESS_PHONE_NUMBER": "O kò tíì fi Ẹ̀rọ-Ìbánísọ̀rọ̀ Iṣẹ́/Òwò rẹ síi",
        "BUSINESS_EMAIL_ADDRESS": "O kò tíì fi Ẹ̀rọ-Àtẹ̀jíṣẹ́ Ímeèli Iṣẹ́ rẹ síi"
      },
      "BUTTONS": {
        "MENU": "Èròja Atọ́kùn",
        "LOYALTY_STAMPS": "Òntẹ̀ Ìṣe-déédé",
        "BUSINESS_PHOTOS": "Àwòrán Nípa Òwò/Iṣẹ́",
        "QR_CODE": "Wo Àwòrán QR Code",
        "CONFIRM": "Fi Ìfiléde Iṣẹ́/Òwò mi Pamọ́",
        "UNDER_CONSTRUCTION": "À ń ṣiṣẹ̀ nípa Èròjà yí l'ọ́wọ́"
      }
    },
    "CONFIGURATION": {
      "LABELS": {
        "SHOP_NAME": "Orúkọ Àyè-Ìtajà",
        "MENU": "Àwọn Èlò Atọ́kùn",
        "ACCEPT_ORDERS_WITHOUT_PAYMENT_MESSAGE": "Gba Ìbèèrè fún Ọjà láì tíì sanwó",
        "ACCEPT_PI_TRANSACTIONS_MESSAGE": "Gba Sísan owó Pi"
      },
      "ADD_PRODUCT_MENU": {
        "LABELS": {
          "ADD_PRODUCT_INTO_SHOP_MESSAGE": "Fi Ọjà sí inú àyè ìtajà rẹ",
          "PRODUCT_NAME": "Orúkọ Ọjà",
          "PRODUCT_IMAGES": "Àwọn Àwòrán Ọjà",
          "ADD_IMAGE": "Fi Àwòrán síi",
          "PRICE": "Iye-owó Ọjà",
          "DESCRIPTION": "Àlàyé nípa Ọjà",
          "FOOD_SERVICE": {
            "TIME_PREPARATION_MESSAGE": "Iye Ìṣẹ́jú tí Óunjẹ yí á tó dé lẹ̀?"
          }
        },
        "BUTTONS": {
          "LOADING": "Ó ń kójọpọ̀ lọ́wọ́..",
          "CONFIRM": "Ó dára": ""
        }
      }
    },
    "ADD_PRODUCT": {
      "LABELS": {
        "PRODUCT_NAME": "Orúkọ Ọjà",
        "PRODUCT_DESCRIPTION": "Àlàyé Ṣókí nípa Ọjà yí",
        "PRODUCT_IMAGES": "Àwọn Àwòrán nípa Ọjà yí",
        "PRODUCT_PRICE": "Iye Owó Ọjà",
        "PRODUCT_QUANTITY": "Iye Ónka Ọjà",
        "SHIPPING_TYPE": "Àwọn Oríṣí Ọ̀nà làti fi Ọjà ránṣẹ́ sí Olùrajà"
      },
      "PLACEHOLDERS": {
        "PRODUCT_IMAGES": "Tẹ ibí láti fi Àwọn Àwòrán nípa Ọjà rẹ síi",
        "PRODUCT_IMAGES_MAX": "Ó kéré jù, Àwòrán Mẹ́ta(tàbí Jubẹ́ẹ́lọ)"
      },
      "VALIDATIONS": {
        "PRODUCT_IMAGES": "O kò tíì fi Àwòrán nípa Ọjà rẹ síì"
      },
      "OPTIONS": {
        "SHIPPING_TYPES": {
          "FREE_SHIPPING": "Fífi Ọjà Ránṣe sí Olùrajà l'ọ́fẹ̀",
          "PAID_SHIPPING": "Sísan Owó Ìfi Ọjà Ránṣẹ́",
          "PICKUP": "Kí Olùrajà wá Gba Ọjà rẹ̀ nì Ilé-Iṣẹ́ wa",
          "PAY_ON_DELIVERY": "Kí Olùrajà san owó Ọjà lẹ́yìn Ìgbà tí a bá gbé Ọjà rẹ̀ lọ fún"
        }
      },
      "BUTTONS": {
        "SUBMIT": "Ó ti parí"
      }
    }
  },
  "SHOPPING": {
    "ORDER_SCREEN": {
      "MENU": "Àwọn Èlò Atọ́kùn",
      "HIGHLIGHT_MESSAGE": "O le ràá lórí afẹ́fẹ́ kí o sanwó lójú-kojú",
      "BUY_NOW_MESSAGE": "Ràá báyì",
      "NO_PRODUCTS_MESSAGE": "Olùtajà yí kò ní Ọjà kankan."
    }
  },
  "PRIVACY_POLICY": {
    "TITLE": "ÌLÀNÀ ÌPA Ọ̀RỌ̀ MỌ́",
    "LAST_UPDATED": "Ìgbà tí a ṣe àtúnṣe kányìn",
    "EMAIL_ADDRESS": "Ẹ̀rọ Àtẹ̀jíṣẹ́ Ímèèlì wa",
    "SECTIONS": {
      "HEADER_1": "Àlàyé Nípa Àkọ́lé yí",
      "CONTENT_1": "Ẹ káábọ̀ sí inú Èròja Káràkátà Map of Pi, èyí tí àwọn Ìgbìmọ Map of Pi dá sílẹ̀, ní Ìfọwọ́sowọ́pọ̀ gbogbo àwùjọ àti àwọn ìkànì Pi. Ìlànà Ìpa Ọ̀rọ̀ mọ́ yí ṣàlàyé bí a ṣe má n gba ọ̀rọ̀, lo ọ̀rọ̀, ṣàfihàn ọ̀rọ̀, àti bí a ṣe má n dáàbò bo àwọn àtẹ̀jíṣẹ́ ọ̀rọ̀ yín nígbà tí ẹ bá n lo Èròja Káràkátà wa.",

      "HEADER_2": "Àwọn Ọ̀rọ̀ tí à ń Gbà",
      "SUBHEADER_2_1": "Ọ̀rọ̀ nípa Ẹni tí ó ńlo Èròjà yí",
      "CONTENT_2_1_1": "Tí ẹ bá fi Orúkọ sílẹ̀ gẹ́gẹ́ bí Olùlo-Èròja Káràkátà yí, a máa ní láti gba Orúkọ yín, Ẹ̀rọ Àtẹ̀jíṣẹ́ Íméélì yín, Àlàjẹ́ tàbí Àpèmọ́-Orúkọ yín, àti àwọn Ọ̀rọ̀ pàtàkì míràn.",
      "CONTENT_2_1_2": "Fún raraarẹ̀ ni Èròja Káràkátà yí máa ní láti gba àwọn Ọ̀rọ̀-àtọ́kasí nípa Ẹ̀rọ Ayára-bí àṣá yín, bíi Irúu Ẹ̀rọ tí ó bá jẹ́, Irúu Irinṣẹ́ àìfojúrí tí ó fí n ṣisẹ́, àti àwọn ọ̀rọ̀ ìtọ́kasí pàtàkì nípa rẹ̀.",
      "SUBHEADER_2_2": "Àwọn Ọ̀rọ̀ Olùtajà",
      "CONTENT_2_2_1": "Àwọn Olùtajà tí wọn ń fi Orúkọ s'ílẹ̀ nínúu Èròja Káràkátà yí máa ní láti fi àwọn Ọ̀rọ̀ nípa Òwò/Iṣẹ́/Ilé-iṣẹ́ wọn s'ílẹ̀, bíi Orúkọ Òwò/Iṣẹ́/Ilé-iṣẹ́ wọn, Agbègbè tí ó wà, àti àwọn ẹ̀rọ ìbánisọ̀rọ̀ tàbí ìlànà láti kàn síwọn.",

      "HEADER_3": "Bí a ṣe máa ńlo àwón Ọ̀rọ̀ tí ẹ fi s'ílẹ̀",
      "SUBHEADER_3_1": "Láti fi ṣe Ìpèsè/Àlékún/Àtúnṣe Iṣẹ́ wa",
      "CONTENT_3_1_1": "À ńlo àwọn ọ̀rọ̀ tí ẹ fi s'ílẹ̀ láti fi ṣe Ìpèsè, Àtúnṣe àti Àlékún iṣẹ́ wa nínú Èròja Káràkátà Map of Pi, bíi gbogbo àwọn èèlò tí Olúrajà àti Olútajà máa máa lò nínúu Èròja Káràkátà yí.",
      "SUBHEADER_3_2": "Ọ̀nà Ìkànsíra-Ẹni",
      "CONTENT_3_2_1": "A máa lo Ẹ̀rọ Àtẹ̀jíṣẹ́ Ímeèlì yín láti máa fún yín ní àwọn Ìròyìn, Àkíyèsí, àti àwọn Ọ̀nà Ìtẹ̀síwájú nípa Èròja Káràkátà Map of Pi.",
      "SUBHEADER_3_3": "Àtúpalẹ̀",
      "CONTENT_3_3_1": "A má ńṣe Àtúpalẹ̀ àwọn Ọ̀rọ̀ tí a gbà làti fi ṣe Àtúnṣe ọnà ìgbàṣiṣẹ́, àwọn èèlò, àti àwọn ǹkan míràn nípa Èròja Káràkátà yi.",

      "HEADER_4": "Ṣíṣe Àfihàn Àwọn Ọ̀rọ̀ tí ẹ fi s'ílẹ̀",
      "SUBHEADER_4_1": "Fún/Pẹ̀lúu Àwọn Olùtajà",
      "CONTENT_4_1_1": "A máa ṣ'àfihàn àwọn Ọ̀rọ̀ tí Olùrajà bá fi s'ílẹ̀ fún àwọn Olùtajà, láti lòó fún mímọ irúu Ọjà tí wọn fẹ́ tà fúnwọn, àti bí wọ́n ṣe máa kàn sí wọn.",
      "SUBHEADER_4_2": "Pẹ̀lúu Ẹnì Kẹ̀ta tàbí Ilé-iṣẹ́ míràn",
      "CONTENT_4_2_1": "A lè ní láti lo àwọn Ọ̀rọ̀ tí a gbà fún ìṣàfihàn pẹ̀lúu Ilé-iṣẹ́ míràn, fún síse-dáada Ẹ̀ròja Káràkátà yí, àti fún Àtúpalẹ̀, àti fùn àwọn ètò pẹ̀lú ílànà láti san owó.",

      "HEADER_5": "Ìgbésẹ̀ Nípa Ètò-Àbò",
      "CONTENT_5_1": "A ti ṣe ètò àbò orì-afẹ́fẹ́ tí ó múná dóko, láti dáábò bo àwọn ọ̀rọ̀ àti ìfiléde yín. Síbẹ̀síbẹ̀ náà, kò tíì sí ìfi-ọ̀rọ̀ ránṣẹ́ tàbí ìfi-ọ̀rọ̀ pamọ́ lóríi ìtàkùn ayélujàra tàbí lóríi afẹ́fẹ́, tí ètò àbo rẹ̀ dájú tán.",

      "HEADER_6": "Àwọn Àṣàyàn Rẹ",
      "CONTENT_6_1": "O lè ṣe àtúnkọ tàbí kí o pa àwọn ọ̀rọ̀-ìfiléde rẹ rẹ́, nì inúu èèlo-ètò Èròjà yí. Tí o bá sì fẹ́, o lè wọ́gi lé àwọn àtẹ̀jìṣẹ́ ì [...]

2024-03-24 08:19 UTC, Ahis24 commented
Nice work sir @swoocn Kindly review the changes at line 91, the translation's title("Confirm") is missing just as I've suggested the changes.
Thanks.

2024-03-24 18:04 UTC, swoocn commented
> Nice work sir @swoocn Kindly review the changes at line 91, the translation's title("Confirm") is missing just as I've suggested the changes. Thanks.

Please see correction.  Thanks, @Ahis24!

2024-03-24 19:40 UTC, Ahis24 commented
![Screenshot_20240324-203528](https://github.com/swoocn/map-of-pi-redux/assets/162028216/1cdacfd6-e569-4781-bc11-d21d5beaf933)

@swoocn kindly refer to the image above

2024-03-24 20:24 UTC, swoocn commented
> ![Screenshot_20240324-203528](https://private-user-images.githubusercontent.com/162028216/316337343-1cdacfd6-e569-4781-bc11-d21d5beaf933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTE4OTAsIm5iZiI6MTcxMTMxMTU5MCwicGF0aCI6Ii8xNjIwMjgyMTYvMzE2MzM3MzQzLTFjZGFjZmQ2LWU1NjktNDc4MS1iYzExLWQyMWQ1YmVhZjkzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQyMDE5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjQ3M2YxNWFhNjUyZTE2ZDBlNmI1YTFjMDUyYmY4YzYyZDZjOWU0MDg4MzAxNjdkNWY5MjNkMjBiZmEyMjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a0aak-DVV23sPRBxmewrLJsbOuH-tkz2qeCtxZ9kKng)
> 
> @swoocn kindly refer to the image above

Alright.  Though, I just took the same confirm translation as the one here: ->

```
"BUTTONS": {
"MENU": "Èròja Atọ́kùn",
"LOYALTY_STAMPS": "Òntẹ̀ Ìṣe-déédé",
"BUSINESS_PHOTOS": "Àwòrán Nípa Òwò/Iṣẹ́",
"QR_CODE": "Wo Àwòrán QR Code",
**"CONFIRM": "Fi Ìfiléde Iṣẹ́/Òwò mi Pamọ́",**
 "UNDER_CONSTRUCTION": "À ń ṣiṣẹ̀ nípa Èròjà yí l'ọ́wọ́"
}
```
Are we still good with this translation then..?

2024-03-24 22:45 UTC, Ahis24 commented
> > ![Screenshot_20240324-203528](https://private-user-images.githubusercontent.com/162028216/316337343-1cdacfd6-e569-4781-bc11-d21d5beaf933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTE4OTAsIm5iZiI6MTcxMTMxMTU5MCwicGF0aCI6Ii8xNjIwMjgyMTYvMzE2MzM3MzQzLTFjZGFjZmQ2LWU1NjktNDc4MS1iYzExLWQyMWQ1YmVhZjkzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQyMDE5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjQ3M2YxNWFhNjUyZTE2ZDBlNmI1YTFjMDUyYmY4YzYyZDZjOWU0MDg4MzAxNjdkNWY5MjNkMjBiZmEyMjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a0aak-DVV23sPRBxmewrLJsbOuH-tkz2qeCtxZ9kKng)
> > @swoocn kindly refer to the image above
> 
> Alright. Though, I just took the same confirm translation as the one here: ->
> 
> ```
> "BUTTONS": {
> "MENU": "Èròja Atọ́kùn",
> "LOYALTY_STAMPS": "Òntẹ̀ Ìṣe-déédé",
> "BUSINESS_PHOTOS": "Àwòrán Nípa Òwò/Iṣẹ́",
> "QR_CODE": "Wo Àwòrán QR Code",
> **"CONFIRM": "Fi Ìfiléde Iṣẹ́/Òwò mi Pamọ́",**
>  "UNDER_CONSTRUCTION": "À ń ṣiṣẹ̀ nípa Èròjà yí l'ọ́wọ́"
> }
> ```
> 
> Are we still good with this translation then..?

@swoocn 
Yes, the translation of this particular section is very correct and OK sir 👌 .
BUT..........

2024-03-24 22:50 UTC, Ahis24 commented
@swoocn 
..But our tribe's Yoruba language is sometimes a bit complicated. The both translations differ because their phrase "Confirm" falls under two different circumstances of action. Let me elaborate further...

Based on the dialog as in the image I sent, the user may tap on the 'Confirm' button while the page is loading, the confirm button here means "Okay = Ó dára"

While the Confirm as from the section which you took above literally means "save my data(Fi Ìfiléde Iṣẹ́/Òwò mi Pamọ́)", based on the section's actions. 

So, the confirm in the both places sensibly translates to two different phrases in our local language, so as for my people to be able to understand and get along accordingly.

So kindly update former request as outlined in the image to avoid confusions sir, and leave the latter section as it is.
Humble Regards.

2024-03-25 02:19 UTC, swoocn commented
> @swoocn ..But our tribe's Yoruba language is sometimes a bit complicated. The both translations differ because their phrase "Confirm" falls under two different circumstances of action. Let me elaborate further...
> 
> Based on the dialog as in the image I sent, the user may tap on the 'Confirm' button while the page is loading, the confirm button here means "Okay = Ó dára"
> 
> While the Confirm as from the section which you took above literally means "save my data(Fi Ìfiléde Iṣẹ́/Òwò mi Pamọ́)", based on the section's actions.
> 
> So, the confirm in the both places sensibly translates to two different phrases in our local language, so as for my people to be able to understand and get along accordingly.
> 
> So kindly update former request as outlined in the image to avoid confusions sir, and leave the latter section as it is. Humble Regards.

Ah, thank you for the information and sorry about the assumption.  I will get this corrected asap!
In the meantime, could you please provide the translation for the following as well?

```
"SEARCH_BY_BUSINESS_PLACEHOLDER": "Search Businesses..",
"SEARCH_BY_PRODUCT_PLACEHOLDER": "Search Products.."
```

2024-03-25 08:40 UTC, Ahis24 commented
> > @swoocn ..But our tribe's Yoruba language is sometimes a bit complicated. The both translations differ because their phrase "Confirm" falls under two different circumstances of action. Let me elaborate further...
> > Based on the dialog as in the image I sent, the user may tap on the 'Confirm' button while the page is loading, the confirm button here means "Okay = Ó dára"
> > While the Confirm as from the section which you took above literally means "save my data(Fi Ìfiléde Iṣẹ́/Òwò mi Pamọ́)", based on the section's actions.
> > So, the confirm in the both places sensibly translates to two different phrases in our local language, so as for my people to be able to understand and get along accordingly.
> > So kindly update former request as outlined in the image to avoid confusions sir, and leave the latter section as it is. Humble Regards.
> 
> Ah, thank you for the information and sorry about the assumption. I will get this corrected asap! In the meantime, could you please provide the translation for the following as well?
> 
> ```
> "SEARCH_BY_BUSINESS_PLACEHOLDER": "Search Businesses..",
> "SEARCH_BY_PRODUCT_PLACEHOLDER": "Search Products.."
> ```

@swoocn 
"SEARCH_BY_BUSINESS_PLACEHOLDER": "Wá Àwọn Iṣẹ́/Òwò Oríṣirísi..",
"SEARCH_BY_PRODUCT_PLACEHOLDER": "Wá Àwọn Ọjà Oríṣirísi.."

2024-03-25 22:02 UTC, merged